paths:
  model: './checkpoint/'

params:
  action: ['follow', 'replan', 'wait']
  hidden_size: 256
  learning_rate: 0.001
  gamma: 0.95
  batch_size: 64
  episode: 1000
  timestep: 3600
  memory_size: 10000
  target_update_frequency: 10
  reward: {'goal': 100, 'deadlock': -50, 'delayed': -1}