_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
action:
    value:
        - follow
        - replan
        - wait
batch_size:
    value: 64
deadlock_penalty:
    value: 50
delayed_penalty:
    value: 1
episode:
    value: 1000
gamma:
    value: 0.95
goal_reward:
    value: 100
hidden_size:
    value: 256
learning_rate:
    value: 0.001
memory_size:
    value: 10000
target_update_freqeuncy:
    value: 10
timestep:
    value: 3600
